baseURL = 'https://garden2k.com/'
locale = 'en-us'
title = 'Garden2k'

[module]
  [[module.imports]]
    path = "github.com/gohugo-ananke/ananke/v2"
    
[params]
  custom_css = ["css/custom.css"]

[mediaTypes]
  [mediaTypes."text/calendar"]
    suffixes = ["ics"]

[outputFormats]
  [outputFormats.ICS]
    mediaType = "text/calendar"
    baseName = "event"
    isPlainText = true
    notAlternative = true

[outputs]
  page = ["HTML"]

[[menus.main]]
  name = "Events Calendar"
  pageRef = "/events"
  weight = 10

[[menus.main]]
  name = "About"
  pageRef = "/about"
  weight = 20

[[menus.main]]
  name = "GitHub"
  url = "https://github.com/garden2k"
  weight = 30