baseURL = 'https://garden2k.com/'
locale = 'en-us'
title = 'Garden2k'

[[module.imports]]
  path = "github.com/mfg92/hugo-shortcode-gallery"

[taxonomies]
  tag = "tags"

[params]
  site_logo = "/images/logo.png"
  favicon = "/favicon.ico"
  nav_button_text = "Download"
  nav_button_url = "https://github.com/seven-obelisks/garden2k"
  custom_css = ["css/styles.css", "css/mobile.css", "css/overrides.css", "css/calendar.css", "css/slider.css"]

[mediaTypes]
  [mediaTypes."text/calendar"]
    suffixes = ["ics"]

[outputFormats]
  [outputFormats.ICS]
    mediaType = "text/calendar"
    baseName = "event"
    isPlainText = true
    notAlternative = true

[outputs]
  page = ["HTML"]
  home = ["HTML", "JSON"]

[[menu.main]]
  name = "Events"
  pageRef = "/events"
  identifier = "events"
  weight = 10
  [menu.main.params]
    description = "Suspendisse rutrum, tellus quis euismod sollicitudin, leo mauris venenatis velit, sed elementum nulla nulla placerat turpis."
    button_text = "View All Events"
    button_url = "/events"
    feature_title = "Stay in the loop"
    feature_text = "Aenean hendrerit ut turpis lacinia feugiat. Nunc nec mi erat. Curabitur magna massa, malesuada ac purus eu."
    feature_button_text = "View Calendar"
    feature_button_url = "/calendar"

[[menu.main]]
  name = "Filtered Events"
  url = "/events/filtered-events"
  parent = "events"
  weight = 10

[[menu.main]]
  name = "Calendar"
  pageRef = "/calendar"
  weight = 20

[[menu.main]]
  name = "Blog"
  pageRef = "/posts"
  weight = 30

[[menu.main]]
  name = "Page Examples"
  identifier = "examples"
  url = "/examples"
  weight = 40
  [menu.main.params]
    description = "In a iaculis lectus, ac blandit quam. Vestibulum porta, justo eu rhoncus consequat, ante leo ornare est, in tincidunt sem lacus a eros."
    button_text = "Browse All Examples"
    button_url = "/examples"
    feature_image = "/uploads/subscribe.png"
    feature_button_url = "https://garden2k.com"

[[menu.main]]
  name = "Banner Example Page"
  url = "/examples/banner-page"
  parent = "examples"
  weight = 10

[[menu.main]]
  name = "Event List Page"
  url = "/examples/listview-page"
  parent = "examples"
  weight = 20

[[menu.main]]
  name = "Mixed Content Page"
  url = "/examples/mixed-page"
  parent = "examples"
  weight = 30

[[menu.main]]
  name = "Photo Content Page"
  url = "/examples/photo-page"
  parent = "examples"
  weight = 40

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 50

[[menu.footer]]
  name = "Explore"
  identifier = "footer-explore"
  weight = 10

[[menu.footer]]
  name = "Events"
  url = "/events"
  parent = "footer-explore"
  weight = 10

[[menu.footer]]
  name = "Calendar"
  url = "/calendar"
  parent = "footer-explore"
  weight = 20

[[menu.footer]]
  name = "Blog"
  url = "/posts"
  parent = "footer-explore"
  weight = 30

[[menu.footer]]
  name = "Resources"
  identifier = "footer-resources"
  weight = 20

[[menu.footer]]
  name = "Page Examples"
  url = "/examples"
  parent = "footer-resources"
  weight = 10

[[menu.footer]]
  name = "About"
  url = "/about"
  parent = "footer-resources"
  weight = 20

[[menu.footer]]
  name = "Login"
  url = "https://garden2k.com/admin"
  weight = 30

[params.social]
  instagram = "https://instagram.com"
  facebook = "https://facebook.com"